# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(1024, 1024))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbltitulo = QtWidgets.QLabel(self.centralwidget)
        self.lbltitulo.setGeometry(QtCore.QRect(310, 140, 161, 20))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setBold(True)
        font.setWeight(75)
        self.lbltitulo.setFont(font)
        self.lbltitulo.setObjectName("lbltitulo")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(214, 212, 297, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnsalir = QtWidgets.QPushButton(self.widget)
        self.btnsalir.setObjectName("btnsalir")
        self.horizontalLayout.addWidget(self.btnsalir)
        self.txtdatos = QtWidgets.QLineEdit(self.widget)
        self.txtdatos.setObjectName("txtdatos")
        self.horizontalLayout.addWidget(self.txtdatos)
        self.btnaceptar = QtWidgets.QPushButton(self.widget)
        self.btnaceptar.setObjectName("btnaceptar")
        self.horizontalLayout.addWidget(self.btnaceptar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuarchivo = QtWidgets.QMenu(self.menubar)
        self.menuarchivo.setObjectName("menuarchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionabrir = QtWidgets.QAction(MainWindow)
        self.actionabrir.setObjectName("actionabrir")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.menuarchivo.addAction(self.actionabrir)
        self.menuarchivo.addAction(self.actionGuardar)
        self.menubar.addAction(self.menuarchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbltitulo.setText(_translate("MainWindow", "MI PRIMER GRÁFICO"))
        self.btnsalir.setText(_translate("MainWindow", "Salir"))
        self.btnaceptar.setText(_translate("MainWindow", "Aceptar"))
        self.menuarchivo.setTitle(_translate("MainWindow", "archivo"))
        self.actionabrir.setText(_translate("MainWindow", "Abrir"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
